"use client";

import { Box, Typography } from "@mui/material";
import React, { useEffect, useState } from "react";
import { Controller, useWatch } from "react-hook-form";
import { CWTextField } from "@/modules/shared/component/FormFields/CWTextField";
import { useCreateSchoolAccount } from "./hook/useCreateSchoolAccount";
import { Button } from "@/modules/shared/component/Button";
import Link from "next/link";
import { CWDropdown } from "@/modules/shared/component/FormFields/CWDropdown";
import ImageUpload from "@/modules/shared/component/ImageUpload/imageUpload";
import { AuthRoutes } from "@/routes/auth.routes";
import { getSchoolPortalBaseDomain } from "@/utils/helper";

const CreateSchoolAccountForm = () => {
  const {
    control,
    handleSubmit,
    isPending,
    countryOptions,
    stateOptions,
    cityOptions,
    selectedCountryValue,
    selectedStateValue,
    isUploadingImage,
    isFormDirty,
    setValue,
  } = useCreateSchoolAccount();

  const [lastAutoGeneratedSubDomain, setLastAutoGeneratedSubDomain] = useState("");
  const schoolName = useWatch({ control, name: "schoolName" });
  const subDomain = useWatch({ control, name: "subDomain" });

  useEffect(() => {
    if ((subDomain || "") === lastAutoGeneratedSubDomain) {
      if (schoolName) {
        const words = schoolName.trim().split(/\s+/);
        let baseSlug = words[0] || "";

        for (let i = 1; i < words.length; i++) {
          if (baseSlug.replace(/[^a-zA-Z0-9]/g, "").length >= 4) {
            break;
          }
          baseSlug += "-" + words[i];
        }

        const slug = baseSlug
          .toLowerCase()
          .replace(/[^a-z0-9-]/g, "")
          .replace(/^-+|-+$/g, "");

        if (subDomain !== slug) {
          setValue("subDomain", slug, { shouldValidate: true });
          setLastAutoGeneratedSubDomain(slug);
        }
      } else if (lastAutoGeneratedSubDomain) {
        setValue("subDomain", "", { shouldValidate: true });
        setLastAutoGeneratedSubDomain("");
      }
    }
  }, [schoolName, subDomain, lastAutoGeneratedSubDomain, setValue]);

  useEffect(() => {
    if (!isFormDirty) return;

    const warningMessage =
      "You have unsaved school details. If you leave now, your account will not be attached to a school yet and your changes will be lost. Do you want to continue?";

    const handleBeforeUnload = (event: BeforeUnloadEvent) => {
      event.preventDefault();
      event.returnValue = warningMessage;
    };

    const handleDocumentClick = (event: MouseEvent) => {
      const target = event.target as HTMLElement | null;
      const linkEl = target?.closest("a[href]") as HTMLAnchorElement | null;
      if (!linkEl) return;
      if (linkEl.target === "_blank") return;
      if (!linkEl.href || linkEl.href.startsWith("javascript:")) return;
      if (linkEl.pathname === window.location.pathname && linkEl.search === window.location.search)
        return;

      const shouldLeave = window.confirm(warningMessage);
      if (!shouldLeave) {
        event.preventDefault();
        event.stopPropagation();
      }
    };

    window.addEventListener("beforeunload", handleBeforeUnload);
    document.addEventListener("click", handleDocumentClick, true);

    return () => {
      window.removeEventListener("beforeunload", handleBeforeUnload);
      document.removeEventListener("click", handleDocumentClick, true);
    };
  }, [isFormDirty]);

  return (
    <Box sx={{ display: "flex", justifyContent: "center", width: "100%" }}>
      <form
        onSubmit={handleSubmit}
        className="flex w-full max-w-[800px] flex-col gap-5 rounded-2xl bg-white p-4 shadow-md sm:gap-6 sm:p-8"
      >
        <Box className="text-center flex flex-col gap-1 w-full">
          <Typography className="!font-bold !text-secondary-text-gray leading-[1.2] !text-2xl">
            Tell us about your school?
          </Typography>
          <Typography className="!text-secondary-text-gray !font-normal !text-sm">
            This helps us personalize your experience.
          </Typography>
        </Box>

        <Box className="flex max-h-[52dvh] flex-col gap-4 overflow-y-auto sm:max-h-[480px]">
          <Box className="border-y border-solid border-border-lightGray flex flex-col gap-5 py-4">
            <Box className="flex flex-col gap-1 border-border-lightGray pb-4">
              <Typography className="text-sm! font-medium!">School Logo</Typography>
              <ImageUpload name="schoolLogoUrl" control={control} label="School Logo" />
            </Box>
            <Box className="flex flex-col gap-3 sm:flex-row">
              <CWTextField
                control={control}
                requiredAsterisk
                name="schoolName"
                label="School Name"
                placeholder="Enter school name"
                labelOnTop
                labelClassName="!text-sm !font-medium !text-input-gray"
                inputClasses="mt-1 !text-xs !h-10 !text-input-gray placeholder:!text-input-gray"
                className="flex-1"
              />
            </Box>
            <CWDropdown
              name="schoolType"
              control={control}
              options={[
                { name: "Pre-School/Child Care", value: "pre_school/child_care" },
                { name: "After School", value: "after_school" },
                { name: "Home Based Care", value: "home_based_care" },
                { name: "Camps", value: "camps" },
              ]}
              isForm
              textFieldProps={{
                label: "School Type",
                labelClassName: "!text-sm !font-medium !text-input-gray",
                placeholder: "Select school type",
                inputClasses: "mt-1 !text-xs !h-10 !text-input-gray",
                labelOnTop: true,
                className: "!w-full",
              }}
              dialogBodyClassName="!p-0"
              maxDialogWidth={100}
            />
            <CWTextField
              control={control}
              requiredAsterisk
              name="maximumEnrolment"
              label="Maximum Enrolment"
              placeholder="Enter maximum enrolment"
              labelOnTop
              labelClassName="!text-sm !font-medium !text-input-gray"
              inputClasses="mt-1 !text-xs !h-10 !text-input-gray placeholder:!text-input-gray"
              className="flex-1"
            />
            <CWTextField
              control={control}
              requiredAsterisk
              name="email"
              label="Email Address"
              placeholder="Enter email address"
              type="email"
              labelOnTop
              labelClassName="!text-sm !font-medium !text-input-gray"
              inputClasses="mt-1 !text-xs !h-10 !text-input-gray placeholder:!text-input-gray"
              className="flex-1"
            />
            <CWTextField
              control={control}
              requiredAsterisk
              name="phoneNumber"
              label="Phone Number"
              placeholder="Enter phone number"
              labelOnTop
              labelClassName="!text-sm !font-medium !text-input-gray"
              inputClasses="mt-1 !text-xs !h-10 !text-input-gray placeholder:!text-input-gray"
              className="flex-1"
            />
            <div>
              <label className="text-sm! font-medium! text-input-gray!">Custom Domain<span className="text-red-500 ml-0.5">*</span></label>
              <Controller
                name="subDomain"
                control={control}

                render={({ field, fieldState: { error } }) => (
                  <>
                    <div
                      className={`flex items-center border rounded-md mt-1 h-10 w-full ${error ? "border-red-500" : "border-gray-300"
                        }`}
                    >
                      <span className="pl-3 text-xs text-[#414141] bg-white h-full flex items-center rounded-l-md whitespace-nowrap select-none">
                        https://
                      </span>
                      <input
                        {...field}
                        type="text"
                        placeholder="your-school"
                        style={{
                          width: `${Math.max((field.value || "").length, 11)}ch`,
                          maxWidth: "100%",
                        }}
                        className="min-w-[40px] border-none outline-none focus:ring-0 text-xs text-input-gray h-full px-1 transition-all duration-200"
                        onChange={(e) => {
                          const cleaned = e.target.value
                            .toLowerCase()
                            .replace(/\s+/g, "-")
                            .replace(/[^a-z0-9-]/g, "");
                          field.onChange(cleaned);
                        }}
                      />
                      <span className="pr-3 text-xs text-[#414141] bg-white h-full flex items-center rounded-r-md whitespace-nowrap select-none">
                        .{getSchoolPortalBaseDomain()}
                      </span>
                    </div>
                    {error && (
                      <p className="text-red-500 text-xs mt-1 ml-3">{error.message}</p>
                    )}
                  </>
                )}
              />
            </div>
            <Box className="flex flex-col gap-3 sm:flex-row">
              <CWDropdown
                name="country"
                control={control}
                options={countryOptions}
                hasSearch
                isForm
                textFieldProps={{
                  label: "Country",
                  labelClassName: "!text-sm !font-medium !text-input-gray",
                  placeholder: "Select country",
                  inputClasses: "mt-1 !text-xs !h-10 !text-input-gray",
                  labelOnTop: true,
                  className: "!w-full",
                }}
                dialogBodyClassName="!p-0"
                maxDialogWidth={120}
              />
              <CWDropdown
                name="state"
                control={control}
                options={stateOptions}
                hasSearch
                isForm
                disabled={!selectedCountryValue}
                textFieldProps={{
                  label: "State",
                  labelClassName: "!text-sm !font-medium !text-input-gray",
                  placeholder: selectedCountryValue ? "Select your state" : "Select country first",
                  inputClasses: "mt-1 !text-xs !h-10 !text-input-gray",
                  labelOnTop: true,
                  className: "!w-full",
                }}
                dialogBodyClassName="!p-0"
                maxDialogWidth={120}
              />
            </Box>
            <Box className="flex flex-col gap-3 sm:flex-row">
              <CWDropdown
                name="city"
                control={control}
                options={cityOptions}
                hasSearch
                isForm
                disabled={!selectedStateValue}
                textFieldProps={{
                  label: "City",
                  labelClassName: "!text-sm !font-medium !text-input-gray",
                  placeholder: selectedStateValue ? "Select city" : "Select state first",
                  inputClasses: "mt-1 !text-xs !h-10 !text-input-gray",
                  labelOnTop: true,
                  className: "!w-full",
                }}
                dialogBodyClassName="!p-0"
                maxDialogWidth={120}
              />
              <CWTextField
                control={control}
                requiredAsterisk
                name="postalCode"
                label="Postal Code"
                placeholder="Enter your postal code"
                labelOnTop
                labelClassName="!text-sm !font-medium !text-input-gray"
                inputClasses="mt-1 !text-xs !h-10 !text-input-gray placeholder:!text-input-gray"
                className="flex-1"
              />
            </Box>
            {/* <Box className="flex flex-row gap-3">
              <CWTextField
                control={control}
                requiredAsterisk
                name="studentResumptionTime"
                type="time"
                label="Student Resumption Time"
                labelOnTop
                placeholder="--:-- --"
                labelClassName="!text-sm !font-medium !text-input-gray"
                inputClasses="mt-1 !text-xs !h-10 !text-input-gray placeholder:!text-input-gray"
                className="flex-1"
              />
              <CWTextField
                control={control}
                requiredAsterisk
                name="schoolClosingTime"
                type="time"
                label="School Closing Time"
                placeholder="--:-- --"
                labelOnTop
                labelClassName="!text-sm !font-medium !text-input-gray"
                inputClasses="mt-1 !text-xs !h-10 !text-input-gray placeholder:!text-input-gray"
                className="flex-1"
              />
            </Box>
            <Box className="flex flex-row gap-3">
              <CWTextField
                control={control}
                requiredAsterisk
                name="staffResumptionTime"
                type="time"
                label="Staff Resumption Time"
                labelOnTop
                placeholder="--:-- --"
                labelClassName="!text-sm !font-medium !text-input-gray"
                inputClasses="mt-1 !text-xs !h-10 !text-input-gray placeholder:!text-input-gray"
                className="flex-1"
              />
              <CWTextField
                control={control}
                requiredAsterisk
                name="staffClosingTime"
                type="time"
                label="Staff Closing Time"
                placeholder="--:-- --"
                labelOnTop
                labelClassName="!text-sm !font-medium !text-input-gray"
                inputClasses="mt-1 !text-xs !h-10 !text-input-gray placeholder:!text-input-gray"
                className="flex-1"
              />
            </Box> */}
            <Box className="flex flex-row gap-3"></Box>
          </Box>
        </Box>

        {/* Submit Button */}
        <Box className="flex flex-row gap-3 justify-end">
          <Button
            className="text-primary-white !rounded-lg"
            fullWidth
            type="submit"
            disabled={isPending || isUploadingImage}
            loading={isPending || isUploadingImage}
            sx={{
              textTransform: "none",
              borderRadius: "8px",
              height: "48px",
              py: 1.2,
              cursor: isPending || isUploadingImage ? "not-allowed" : "pointer",
            }}
          >
            {isPending || isUploadingImage ? "Creating School..." : "Get Started"}
          </Button>
        </Box>

        <Box className="flex flex-row gap-3 justify-center !text-sm">
          Already have an account?{" "}
          <Link href={AuthRoutes.selectRole} className="!text-brandColor-active !font-semibold">
            Login
          </Link>
        </Box>
      </form>
    </Box>
  );
};

export default CreateSchoolAccountForm;
