/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useMemo } from "react";
import { CWTextField } from "@/modules/shared/component/FormFields/CWTextField";
import { CWTextArea } from "@/modules/shared/component/FormFields/CWTextArea";
import { CWDropdown } from "@/modules/shared/component/FormFields/CWDropdown";
import { AllTourFormData, durationOptions } from "../tour.constants";
import { Control, UseFormGetValues, UseFormSetValue, Controller } from "react-hook-form";
import { useQueryService } from "@/utils/hooks/useQueryService";
import { schoolDynamicEndpoints } from "@/services/school.service";
import { GetSchoolResponse } from "@/services/school.service";
import { getSchoolFromCookie, getSchoolPortalBaseDomain, getUserRoleFromCookie } from "@/utils/helper";
import { useWatch } from "react-hook-form";
import { useEffect, useState } from "react";

interface BasicInfoProps {
  control: Control<AllTourFormData>;
  setValue: UseFormSetValue<AllTourFormData>;
  getValues: UseFormGetValues<AllTourFormData>;
}

const BasicInfo = ({ control, setValue, getValues }: BasicInfoProps) => {
  const school = getSchoolFromCookie();
  const userRole = getUserRoleFromCookie();
  const isSystemAdmin = userRole?.toLowerCase() === "systemadmin";

  const { data: schoolData } = useQueryService<GetSchoolResponse, any>({
    service: schoolDynamicEndpoints.getParticularSchool(),
    options: {
      enabled: !isSystemAdmin,
    },
  });

  const subDomain = (schoolData?.school?.subDomain || school?.subDomain || "").trim();
  const URL_PREFIX = `https://${subDomain}.${getSchoolPortalBaseDomain()}/tour-events/`;

  const locationOptions = useMemo(() => {
    const address = schoolData?.school?.address;
    const schoolName = schoolData?.school?.schoolName;
    
    if (address) {
      return [{ name: `${address} (Default)`, value: address }];
    } else if (schoolName) {
      return [{ name: `${schoolName} (Default)`, value: schoolName }];
    }
    return [];
  }, [schoolData?.school]);

  useEffect(() => {
    const defaultLocation = locationOptions[0]?.value;
    const currentLocation = getValues("basicInfo.location");
    
    if (defaultLocation && !currentLocation) {
      setValue("basicInfo.location", defaultLocation, { shouldValidate: true });
    }
  }, [locationOptions, getValues, setValue]);

  const [randomSuffix] = useState(() => Math.floor(1000 + Math.random() * 9000));
  const [lastAutoGeneratedUrl, setLastAutoGeneratedUrl] = useState("");
  const title = useWatch({ control, name: "basicInfo.title" });
  const url = useWatch({ control, name: "basicInfo.url" });

  useEffect(() => {
    if ((url || "") === lastAutoGeneratedUrl) {
      if (title) {
        const slug = title
          .toLowerCase()
          .trim()
          .replace(/[^a-z0-9\s-]/g, "")
          .replace(/[\s-]+/g, "-")
          .replace(/^-+|-+$/g, "");

        const newUrl = slug ? `${slug}-${randomSuffix}` : "";
        
        // Only update if it actually changes to prevent infinite loops
        if (url !== newUrl) {
          setValue("basicInfo.url", newUrl, { shouldValidate: true });
          setLastAutoGeneratedUrl(newUrl);
        }
      } else if (lastAutoGeneratedUrl) {
        setValue("basicInfo.url", "", { shouldValidate: true });
        setLastAutoGeneratedUrl("");
      }
    }
  }, [title, url, lastAutoGeneratedUrl, randomSuffix, setValue]);
  return (
    <div className="px-6 py-5">
      <div className="bg-white sm:p-6 space-y-6">
        <div className="grid grid-cols-1 gap-5">
          <CWTextField
            control={control}
            name="basicInfo.title"
            label="Tour Title"
            placeholder="Enter tour title"
            labelOnTop
            requiredAsterisk
            labelClassName="!text-sm !font-semibold !text-input-gray"
            inputClasses="mt-1 !text-sm !h-10 !text-input-gray"
            className="w-full"
          />

          <CWTextArea
            control={control}
            name="basicInfo.description"
            label="Tour Description"
            placeholder="Enter brief description"
            labelOnTop
            requiredAsterisk
            labelClassName="!text-sm !font-semibold !text-input-gray"
            inputClasses="mt-1 !text-xs !text-input-gray !h-18"
            className="w-full"
          />
          <div>
            <label className="text-sm! font-semibold! text-input-gray!">URL<span className="text-red-500 ">*</span></label>
            <Controller
              name="basicInfo.url"
              control={control}
              render={({ field, fieldState: { error } }) => (
                <>
                  <div
                    className={`flex flex-col gap-0 rounded-md mt-1 w-full border md:flex-row md:items-stretch md:gap-0 overflow-hidden ${
                      error ? "border-red-500" : "border-gray-300"
                    }`}
                  >
                    <span className="px-3 py-2 text-xs text-gray-500 bg-gray-50 break-all md:break-normal md:whitespace-nowrap md:flex md:items-center md:shrink-0 md:border-r md:border-gray-300">
                      {URL_PREFIX}
                    </span>
                    <input
                      {...field}
                      type="text"
                      placeholder="URL"
                      className="min-h-10 w-full min-w-0 border-0 border-t border-gray-200 px-3 py-2 text-xs text-input-gray outline-none focus:ring-0 md:border-t-0 md:flex-1"
                      onChange={(e) => {
                        const cleanedValue = e.target.value
                          .toLowerCase()
                          .replace(/\s+/g, "-")
                          .replace(/[^a-z0-9-]/g, "");
                        field.onChange(cleanedValue);
                      }}
                    />
                  </div>
                  {error && (
                    <p className="text-red-500 text-xs mt-1 ml-3">{error.message}</p>
                  )}
                </>
              )}
            />
          </div>
          <div className="w-full border-t border-[#008080]/20 "></div>

          <div>
            <CWDropdown
              name="basicInfo.duration"
              control={control}
              options={durationOptions}
              isForm
              requiredAsterisk
              textFieldProps={{
                label: "Durations",
                labelClassName: "!text-sm !font-semibold !text-input-gray",
                placeholder: "Select duration",
                inputClasses: "mt-1 !text-sm !h-10 !text-input-gray",
                labelOnTop: true,
                className: "!w-full",
              }}
              dialogBodyClassName="!p-2 !overflow-hidden"
            />
            <div className="w-full border-t border-[#008080]/20 mt-6"></div>
          </div>

          <div>
            <Controller
              name="basicInfo.location"
              control={control}
              render={({ field }) => (
                <CWDropdown
                  name="basicInfo.location"
                  control={control}
                  options={locationOptions}
                  isForm
                  requiredAsterisk
                  value={field.value}
                  onChangeValue={(value) => {
                    field.onChange(value);
                  }}
                  textFieldProps={{
                    label: "Location",
                    labelClassName: "!text-sm !font-semibold !text-input-gray",
                    placeholder: "Select location",
                    inputClasses: "mt-1 !text-sm !h-10 !text-input-gray",
                    labelOnTop: true,
                    className: "!w-full",
                  }}
                  dialogBodyClassName="!p-2 !overflow-hidden"
                />
              )}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default BasicInfo;
