export enum AuthRoutes {
  home = "/",
  root = "/auth",
  selectRole = `${root}/select-role`,
  role = `${root}/role`,
  login = `${root}/login`,
  register = `${root}/register`,
  forgotPassword = `${root}/forgotPassword`,
  resendResetPassword = `${root}/resend-reset-password`,
  verifyToken = `${root}/verifyToken`,
  resetPassword = `${root}/reset-password`,
  verifyEmail = `${root}/verify-email`,
  resendEmailVerification = `${root}/resend-email-verification`,
  refreshToken = `${root}/refresh-token`,
  createNewPassword = `${root}/create-new-password`,
  createSchoolAccount = `${root}/create-school-account`,
  parentGetStarted = `${root}/parent-get-started`,
}
