export enum DashboardRoutes {
  root = "/admin",
  dashboard = "/admin/dashboard",
  settings = "/admin/settings",
  profileSettings = "/admin/settings/profile",
  accountSecuritySettings = "/admin/settings/security",
  notificationSetting = "/admin/settings/notifications",
  permissionSettings = "/admin/settings/permission",
  rolesSettings = "/admin/settings/roles",
  publicLinksSetting = "/admin/settings/public-links",
  paymentMethodSetting = "/admin/settings/payment-method",
  billings = "/admin/settings/billings",
  plans = "/admin/settings/billings/plans",
  billingInvoices = "/admin/settings/billings/invoices",
  billingPayments = "/admin/settings/billings/payments",
}
